---
title: "Assignment 1: Introduction to Data Exploration"
author: "Henry Park"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Exploration. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have some previous experience visualizing data in R through a statistics course, and I have performed data analysis fairly often through research experiences. However, I haven't taken many intensive, dedicated courses on understanding statistical software. 

2. Are there any components of the course about which you feel confident?

> Answer: I feel fairly confident about the analysis portion of the course--understanding patterns in data, drawing conclusions, etc. This was a skill that was demanded often in research so I think I'm more familiar with this than other components of the class. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: I'm most apprehensive about the technical aspects--getting R to work, knowing what are the right steps to take in a lab project, and figuring out how to troubleshoot errors. I'm hoping I make a lot of progress on these things this semester. 


## 2) GitHub

Go over Tasks 1.1. through 1.6 on Course Setup page. Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/hp140/EDE_R_Lab_F26

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
